"""Public interface of the profile module."""

from modules.profile.models import (
    AIPreferences,
    ApplicationPreferences,
    Certification,
    ChunkWrite,
    CompanyPreferences,
    CompanySize,
    DiscoveryPreferences,
    DiscoverySource,
    Education,
    Experience,
    Personal,
    Preferences,
    Profile,
    ProfileContent,
    ProfileCreate,
    ProfileLink,
    ProfileRead,
    ProfileUpdate,
    ResumeChunkText,
    SkillGroup,
    TargetPreferences,
)
from modules.profile.router import router
from modules.profile.service import (
    ChunkNotFound,
    ProfileExists,
    ProfileNotFound,
    create_profile,
    get_chunk,
    get_chunks,
    get_profile,
    replace_chunks,
    update_profile,
)

NAME = "profile"

__all__ = [
    "NAME",
    "AIPreferences",
    "ApplicationPreferences",
    "Certification",
    "ChunkNotFound",
    "ChunkWrite",
    "CompanyPreferences",
    "CompanySize",
    "DiscoveryPreferences",
    "DiscoverySource",
    "Education",
    "Experience",
    "Personal",
    "Preferences",
    "Profile",
    "ProfileContent",
    "ProfileCreate",
    "ProfileExists",
    "ProfileLink",
    "ProfileNotFound",
    "ProfileRead",
    "ProfileUpdate",
    "ResumeChunkText",
    "SkillGroup",
    "TargetPreferences",
    "create_profile",
    "get_chunk",
    "get_chunks",
    "get_profile",
    "replace_chunks",
    "router",
    "update_profile",
]
