"""Public interface of the jobpilot_api tool server."""

from mcp_servers.jobpilot_api.client import (
    JobPilotApiError,
    chunk_stats,
    create_job,
    get_base_resume,
    get_description,
    get_description_for_job,
    get_job,
    get_match,
    get_profile,
    link_description,
    list_pending_chunks,
    list_raw_descriptions,
    list_unscored_jobs,
    reindex_profile,
    search_chunks,
    set_description_status,
    set_token,
    store_chunk_embeddings,
    store_resume,
    update_job,
    write_match,
)

NAME = "jobpilot_api"

__all__ = [
    "NAME",
    "JobPilotApiError",
    "chunk_stats",
    "create_job",
    "get_base_resume",
    "get_description",
    "get_description_for_job",
    "get_job",
    "get_match",
    "get_profile",
    "link_description",
    "list_pending_chunks",
    "list_raw_descriptions",
    "list_unscored_jobs",
    "reindex_profile",
    "search_chunks",
    "set_description_status",
    "set_token",
    "store_chunk_embeddings",
    "store_resume",
    "update_job",
    "write_match",
]
